---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo = TRUE}
unzip("./activity.zip")
activity <- read.csv("./activity.csv")
activity$date <- as.Date(activity$date, "%Y-%m-%d")
```

## What is mean total number of steps taken per day?
```{r echo = TRUE, message = FALSE, warning = FALSE}
library(dplyr)
dailySum <- activity %>%
        group_by(date) %>%
        summarise(date = unique(date),
                  steps = sum(steps, na.rm = TRUE))
library(ggplot2)
g1 <- ggplot(dailySum, aes(x = steps)) + 
        geom_histogram(color = "black", fill = "darkblue", 
                       breaks = seq(0, 22500, by = 2500)) + 
        labs(title = "Total Number of Steps Taken Daily", 
             x = "Steps") + 
        theme_bw()
print(g1)
mean(dailySum$steps)
median(dailySum$steps)
```

## What is the average daily activity pattern?
```{r echo = TRUE, message = FALSE, warning = FALSE}
intMean <- activity %>%
        group_by(interval) %>%
        summarise(interval = unique(interval),
                  steps = mean(steps, na.rm = TRUE))
g2 <- ggplot(intMean, aes(x = interval, y = steps)) + 
        geom_line() + 
        labs(title = "Total Number of Steps Per 5-Minute Interval", 
             x = "Time Interval", 
             y = "Steps") + 
        theme_bw()
print(g2)
intMean[which.max(intMean$steps), ]$interval
```

## Imputing missing values
```{r echo = TRUE, message = FALSE, warning = FALSE}
sum(is.na(activity$steps))
impute <- intMean$steps[match(intMean$interval, activity$interval)]
activity2 <- activity %>% mutate(steps = ifelse(is.na(steps), impute, steps))
dailySum2 <- activity2 %>%
        group_by(date) %>%
        summarise(date = unique(date),
                 steps = sum(steps))
g3 <- ggplot(dailySum2, aes(x = steps)) + 
        geom_histogram(color = "black", fill = "darkblue", 
                       breaks = seq(0, 22500, by = 2500)) + 
        labs(title = "Total Number of Steps Taken Daily", 
             x = "Steps") + 
        theme_bw()
print(g3)
mean(dailySum2$steps)
median(dailySum2$steps)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r echo = TRUE, message = FALSE, warning = FALSE}
activity2 <- activity2 %>% mutate(day = as.factor(ifelse(weekdays(date) %in% c("Saturday", "Sunday"), "weekend", "weekday")))
intMean2 <- activity2 %>%
        group_by(interval, day) %>%
        summarise(interval = unique(interval),
                  steps = mean(steps),
                  day = unique(day))
g4 <- ggplot(intMean2, aes(x = interval, y = steps)) + 
        geom_line() +
        facet_grid(day ~ .) +
        labs(title = "Total Number of Steps Per 5-Minute Interval", 
             x = "Time Interval", 
             y = "Steps") + 
        theme_bw()
print(g4)
```